### ISSUE TITLE
Error in network modules

### ISSUE THREAD

**Issue by gaurav00700** [tangtaogo/alignmif#2]
Hi @tangtaogo Thank you for amazing work and releasing the code . 
I am trying to train the model but It seems there is error at following lines of network modules . 

https://github.com/tangtaogo/alignmif/blob/5aa9873839a852f3ad06cdbdcf2393aa5061d443/lidarnerf/nerf/network_tcnn_alignmif.py#L266
https://github.com/tangtaogo/alignmif/blob/5aa9873839a852f3ad06cdbdcf2393aa5061d443/lidarnerf/nerf/network_tcnn_mif.py#L223

**Comment by tangtaogo** [comment]
Sorry, as mentioned in the readme, I was in a hurry to release the code earlier and there were some areas that were not cleaned up. I just updated the code
