### ISSUE TITLE
Is it multi-stage training?

### ISSUE THREAD

**Issue by chenyuntc** [tangtaogo/alignmif#3]
Hi, I'm trying to run the training. 

```
# single modality
python main_alignmif.py -L --workspace kitti360-1908/lidar --enable_lidar --config configs/kitti360_1908.txt
python main_alignmif.py -L --workspace kitti360-1908/rgb --enable_rgb --config configs/kitti360_1908.txt
# multimodality implicit fusion
python main_alignmif.py -L --workspace kitti360-1908/mif --enable_rgb --enable_lidar --config configs/kitti360_1908.txt --network mif
# aligmif 
python main_alignmif.py -L --workspace kitti360-1908/alignmif --enable_lidar --enable_rgb --config configs/kitti360_1908.txt --ckpt kitti360-1908/lidar/checkpoints/alignmif_ep0500.pth --activate_levels 8 --network alignmif
```

I'm curious, do I need to run single modality first? But single modality failed with 

```
main_alignmif.py 305 main
assert opt.enable_lidar and opt.enable_rgb, "single modality training"

AssertionError:
single modality training
```
 
If I run alignif directly, what checkpoint should I use?

**Comment by chenyuntc** [comment]
Also it's a bit confusing here, is it a typo here? what does the `if` and `elif` branch  refer to? 
https://github.com/tangtaogo/alignmif/blob/main/main_alignmif.py#L305,L309

**Comment by booker-max** [comment]
Similarly, I had this problem, have you solved it now?

**Comment by booker-max** [comment]
我将代码改成如下形式
![image](https://github.com/user-attachments/assets/0f2f2151-fc6f-4d96-a023-7e138848bb02)
此时运行 python main_alignmif.py -L --workspace kitti360-3353/lidar --enable_lidar --config configs/kitti360_3353.txt仍然报错，错误为 AttributeError: 'NeRFNetwork' object has no attribute 'encoder_dir'

**Comment by tangtaogo** [comment]
I'm very sorry for any inconvenience caused. As mentioned in the readme, I rushed the code release, resulting in some areas that were not properly organized or cleaned.  I will update the code today.

**Comment by tangtaogo** [comment]
> Hi, I'm trying to run the training.
> 
> ```
> # single modality
> python main_alignmif.py -L --workspace kitti360-1908/lidar --enable_lidar --config configs/kitti360_1908.txt
> python main_alignmif.py -L --workspace kitti360-1908/rgb --enable_rgb --config configs/kitti360_1908.txt
> # multimodality implicit fusion
> python main_alignmif.py -L --workspace kitti360-1908/mif --enable_rgb --enable_lidar --config configs/kitti360_1908.txt --network mif
> # aligmif 
> python main_alignmif.py -L --workspace kitti360-1908/alignmif --enable_lidar --enable_rgb --config configs/kitti360_1908.txt --ckpt kitti360-1908/lidar/checkpoints/alignmif_ep0500.pth --activate_levels 8 --network alignmif
> ```
> 
> I'm curious, do I need to run single modality first? But single modality failed with
> 
> ```
> main_alignmif.py 305 main
> assert opt.enable_lidar and opt.enable_rgb, "single modality training"
> 
> AssertionError:
> single modality training
> ```
> 
> If I run alignif directly, what checkpoint should I use?

Sorry for the delay in response. Yes, we employ multi-stage training as our SGI module requires a pre-trained lidar-nerf as initialization. I will update the code and readme today.
